development:
  bucket: LEASIFY
  access_key_id: AKIAIK7L57MTKL3JUDRA
  secret_access_key: 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
test:
  bucket: LEASIFY
  access_key_id: AKIAIK7L57MTKL3JUDRA
  secret_access_key: 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
production:
  bucket: LEASIFY
  access_key_id: AKIAIK7L57MTKL3JUDRA
  secret_access_key: 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