development:
  bucket: LEASIFY
  access_key_id: AKIAIWAVU4SRETBA4IYA
  secret_access_key: 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
test:
  bucket: LEASIFY
  access_key_id: AKIAIWAVU4SRETBA4IYA
  secret_access_key: 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
production:
  bucket: LEASIFY
  access_key_id: AKIAIWAVU4SRETBA4IYA
  secret_access_key: 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